apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdevices.iot.example.com
spec:
  group: iot.example.com
  names:
    kind: XDevice
    plural: xdevices
  claimNames:
    kind: XDeviceClaim
    plural: xdeviceclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    replicas:
                      type: integer
                    interval:
                      type: integer

